name: nova_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6

  # Camera & Permissions
  
  permission_handler: ^11.0.1
  
  # Object Detection (YOLO - Yellow Box)
  flutter_vision: ^1.1.4
  
  # Service Locator
  get_it: ^9.2.0
  shake: any

  flutter_tts: ^3.8.5      # For Voice Over
  vibration: ^1.7.7         # For Haptic Feedback
  sensors_plus: ^5.0.0      # For Shake Detection
  google_fonts: ^6.1.0      # For Professional Typography
  camera: ^0.10.5+9         # (Keep your existing camera dependency)

  # ðŸš€ GOOGLE AI PACKAGES (Face & Text)
  google_mlkit_object_detection: ^0.11.0
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_face_detection: ^0.9.0
  
  # Text to Speech
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# -----------------------------------------
# FLUTTER CONFIGURATION
# -----------------------------------------
flutter:
  uses-material-design: true

  # âœ… YOUR ASSETS ARE REGISTERED HERE
  assets:
    - assets/models/yolov8n.tflite
    - assets/models/labels.txt